### ISSUE TITLE
Building via Github Action

### ISSUE THREAD

**Issue by jrock2004** [empress/empress-blog#121]
I am trying to build via GitHub action but I am getting the following error

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
  - configuration.target should be one of these:
    "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | "electron-preload" | function
    -> Environment to build for
    Details:
     * configuration.target should be one of these:
     "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | "electron-preload"
     * configuration.target should be an instance of function
  ```

Here is my GitHub action

```
name: 'Netlify Deploy'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEPLOY: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Clearing out dir
        run: rm -Rf node_modules package-lock.json
      - name: Running NPM Install
        run: npm install
      - name: Build Production
        run: npm run build
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: "dsfsdfsdfsdfsdfds"
          NETLIFY_DEPLOY_MESSAGE: "${{ github.event.head_commit.message }}"
          NETLIFY_DEPLOY_TO_PROD: ${{ github.event_name == 'push' && true || false }}
          BUILD_DIRECTORY: dist
```

Not sure why this erroring out
